name: 'build-iso'
on:
  pull_request:

env:
  ##### EDIT ME #####
  iso-profiles-git: https://github.com/bennibacktbackwaren/custom-manjaro-iso-profiles
  version: build-${{ github.event.number }}
  ###################

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: delete test-release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ env.version }} -y --repo ${{ github.repository }} || exit 0
          git push --delete origin ${{ env.version }}
  build-release:
    runs-on: ubuntu-22.04
    needs: [cleanup]
    strategy:
      matrix:
        ##### EDIT ME #####
        EDITION: [kde]
        BRANCH: [stable]
        SCOPE: [full]
        ###################
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - id: image-build
        uses: ./
        with:
          iso-profiles-repo: ${{ env.iso-profiles-git }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ env.version }}
          release-tag: ${{ env.version }}
          # custom-repo: 
          office-chooser: true
          build-mirror: ${{ secrets.BUILD_MIRROR }}
