name: 'cleanup-test-release'
on:
  pull_request:
    types: [closed]

env:
  version: test-release-${{ github.event.number }}
  edition: xfce

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: delete test-release for closed pr
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ env.version }} -y --repo ${{ github.repository }} || exit 0
      - name: delete cdn77 test upload
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -t rsa ${{ secrets.CDN_HOST }} >> /home/runner/.ssh/known_hosts
          sshpass -p "${{ secrets.CDN_PWD }}" rsync --mkpath --delete -vaP --stats -e ssh $(mktemp) ${{ secrets.CDN_USER }}@${{ secrets.CDN_HOST }}:/www/${{ env.edition }}/${{ env.version }}
