name: 'iso_build'

# Disallow multiple parallel runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Allow the upload of releases
permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-20.04
    steps:
      - id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}      
  release:
    runs-on: ubuntu-20.04
    needs: prepare-release    
    strategy:
      matrix:
        ##### EDIT ME #####      
        EDITION: [kde]
        BRANCH: [stable]
        SCOPE: [full]
        ###################       
    steps:
      - id: image-build
        uses: bennibacktbackwaren/custom-manjaro-iso-action@main
        with:
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: "r${{ needs.prepare-release.outputs.release_tag }}"
          kernel: linux66
          code-name: "Mangio"
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      - name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
