name: 'build-test'
on:
  pull_request:

env:
  ##### EDIT ME #####
  codename: Ornara
  iso-profiles-git: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles
  version: test-release-${{ github.event.number }}
  ###################

jobs:
  build-release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ##### EDIT ME #####
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [full, minimal]
        KERNEL: [linux510]
        ###################
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: delete test-release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ env.version }} -y --repo ${{ github.repository }} || exit 0
      - id: cache-key
        run: echo "::set-output name=key::package-cache-$(/bin/date -u "+%Y%U")"
        shell: bash
      - id: cache
        uses: actions/cache@v2
        with:
          path: package-cache
          key: ${{ steps.cache-key.outputs.key }}-${{ matrix.edition }}-${{ matrix.branch }}-${{ matrix.kernel }}-${{ matrix.scope }}
          restore-keys:  |
            ${{ steps.cache-key.outputs.key }}-${{ matrix.edition }}-${{ matrix.branch }}-${{ matrix.kernel }}-${{ matrix.scope }}
            ${{ steps.cache-key.outputs.key }}-${{ matrix.edition }}-${{ matrix.branch }}-${{ matrix.kernel }}-
            ${{ steps.cache-key.outputs.key }}-${{ matrix.edition }}-${{ matrix.branch }}-
            ${{ steps.cache-key.outputs.key }}-${{ matrix.edition }}-
      - id: copy-cache-to-target
        if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: sudo cp --verbose --force --recursive ./package-cache/* /var/cache/pacman/pkg
      - id: image-build
        uses: ./
        with:
          iso-profiles-repo: ${{ env.iso-profiles-git }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ env.version }}
          kernel: ${{ matrix.kernel }}
          code-name: ${{ env.codename }}
          release-tag: ${{ env.version }}
          gpg-secret-key-base64: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          gpg-passphrase: 1234
          cdn77-host: ${{ secrets.CDN_HOST }}
          cdn77-user: ${{ secrets.CDN_USER }}
          cdn77-pwd: ${{ secrets.CDN_PWD }}
      - id: copy-cache-target-to-cache
        run: |
          mkdir -p package-cache
          sudo cp --verbose --force --recursive /var/cache/pacman/pkg/* ./package-cache