name: 'build-test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: delete test-release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete test-release-${{github.event.number}} -y --repo ${{ github.repository }} || exit 0
      - id: image-build
        uses: ./
        with:
          iso-profiles-repo: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles
          edition: xfce
          branch: stable
          scope: minimal
          version: "21.0"
          kernel: linux510
          code-name: Ornara
          release-tag: test-release-${{github.event.number}}
          gpg-secret-key-base64: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          gpg-passphrase: 1234